"""Web-Terminal: echte Bash-Shell über WebSocket + PTY."""
import os
import asyncio
import fcntl
import termios
import struct
import signal
import shutil
import shlex

try:
    import ptyprocess
    HAS_PTY = True
except ImportError:
    HAS_PTY = False


TMUX_SESSION = "runvard"
DATA_DIR = os.environ.get("RUNVARD_DATA_DIR", "/opt/runvard/data")
TERMINAL_BASHRC = os.path.join(DATA_DIR, "terminal.bashrc")


def ensure_terminal_bashrc(path=None):
    """Create the shell rc used by the persistent web terminal."""
    path = path or TERMINAL_BASHRC
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        return path
    content = r'''# Generated by runvard for the persistent web terminal.
if [ -r "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
fi

export HISTFILE="${HISTFILE:-$HOME/.bash_history}"
export HISTSIZE="${HISTSIZE:-20000}"
export HISTFILESIZE="${HISTFILESIZE:-40000}"
export HISTCONTROL="${HISTCONTROL:-ignoredups:erasedups}"
shopt -s histappend cmdhist

__runvard_history_sync() {
  builtin history -a
  builtin history -n
}

case ";${PROMPT_COMMAND:-};" in
  *";__runvard_history_sync;"*) ;;
  *) PROMPT_COMMAND="__runvard_history_sync${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
esac
'''
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    os.chmod(path, 0o644)
    return path


class TerminalSession:
    """Eine PTY-Shell-Session, an einen WebSocket gebunden."""

    def __init__(self, shell="/bin/bash", cwd="/root", argv=None, persistent=False):
        self.shell = shell
        self.cwd = cwd if os.path.isdir(cwd) else "/"
        self.argv = argv
        self.persistent = persistent
        self.proc = None

    def command(self):
        if self.argv:
            return self.argv
        if self.persistent and shutil.which("tmux"):
            rcfile = ensure_terminal_bashrc()
            shell_cmd = f"{shlex.quote(self.shell)} --rcfile {shlex.quote(rcfile)}"
            script = "\n".join([
                f"if ! tmux has-session -t {shlex.quote(TMUX_SESSION)} 2>/dev/null; then",
                "  tmux new-session -d "
                f"-s {shlex.quote(TMUX_SESSION)} "
                f"-c {shlex.quote(self.cwd)} "
                f"{shlex.quote(shell_cmd)}",
                "fi",
                f"tmux set-option -t {shlex.quote(TMUX_SESSION)} status off",
                f"exec tmux attach-session -t {shlex.quote(TMUX_SESSION)}",
            ])
            return ["/bin/bash", "-lc", script]
        return [self.shell]

    def start(self):
        if not HAS_PTY:
            raise RuntimeError("ptyprocess nicht installiert")
        env = os.environ.copy()
        env["TERM"] = "xterm-256color"
        self.proc = ptyprocess.PtyProcess.spawn(
            self.command(), cwd=self.cwd, env=env, dimensions=(24, 80)
        )

    def write(self, data: str):
        if self.proc and self.proc.isalive():
            self.proc.write(data.encode())

    def read(self, size=1024):
        try:
            return self.proc.read(size).decode(errors="replace")
        except EOFError:
            return None

    def resize(self, rows: int, cols: int):
        if self.proc and self.proc.isalive():
            try:
                fcntl.ioctl(self.proc.fd, termios.TIOCSWINSZ,
                            struct.pack("HHHH", rows, cols, 0, 0))
            except OSError:
                pass

    def alive(self):
        return self.proc is not None and self.proc.isalive()

    def kill(self):
        if self.proc and self.proc.isalive():
            try:
                self.proc.kill(signal.SIGTERM)
            except Exception:
                pass


async def pty_to_ws(session: TerminalSession, websocket):
    """Liest fortlaufend aus der PTY und sendet an den WebSocket."""
    loop = asyncio.get_event_loop()
    while session.alive():
        data = await loop.run_in_executor(None, session.read, 1024)
        if data is None:
            break
        try:
            await websocket.send_text(data)
        except Exception:
            break
